### ISSUE TITLE
Sync Download

### ISSUE THREAD

**Issue by DarioN1** [noserati/WebBrowser#2]
Hello noserati and thanks for your precious work.

Is there a way to convert the webbrowser in order to make Sync Page Download ?

I ask this because I need to get the page content from an homepage generated by Javascript and then I need to simulate some clicks on DIV in order to load other pages and the parse them too.

Using Async Download I'm not able to do it....

Thanks again
Dario

**Comment by noseratio** [comment]
Not sure blocking is the best way to do what you want, but to answer your question, you simple use `apartment.Invoke` (sync call) or `apartment.Run(...).Wait` as apposed to async calls.

**Comment by DarioN1** [comment]
Thanks noserati,

So if I had understood, I have to change:

```
string html = await apartment.Run(() =>
                            webBrowser.NavigateAsync(url, navigationToken), navigationToken);

```
WITH:

                        apartment.Run(() =>
                            webBrowser.NavigateAsync(url, navigationToken), navigationToken).Wait();

But how do I get the output Html ?
.Wait() method returns void... Sorry for this noob question but I'm totally new on sync and async tasks...

My purpose is to scrap a website that is entirelly generated by Javascript, so I have to load the homepage and then, simulate different clicks on DIV in order to load and get subcontent...

I'm on the right way ?

Thanks

**Comment by noseratio** [comment]
You can use `.Result` instead of `.Wait()`. Or better yet, embrace `async/await` everywhere within your automation code, and just do `Wait` once at the top level (e..g, in `Main` for a console app).

**Comment by DarioN1** [comment]
Thanks noserati,
I tryed .Result() and I get the HTML but... Is just simple static HTML without the HTML rendered by Javascript...

May be I'm totally out of the way an this is not the place to discuss what I have to do, because just to sum, I have to create a console application that implement browser automation:

Load home page, click on divs and parse HTML....

I'm a bit confused...

**Comment by noseratio** [comment]
This shouldn't be a problem. I cannot write the code for you, but have a look [here](http://stackoverflow.com/a/20934538/1768303) and [here](http://stackoverflow.com/a/19063643/1768303).
